server:
  port: 8004
spring:
  application:
    name: cloud-shop-content

  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: ${spring.application.name}

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/pinyougoudb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: "root"
    password: "0701"

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cloud.shop.entitlse

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
